### PR TITLE
Fix bug: parse object that contains value of undefined

### PR DESCRIPTION
**Pull request by Ovilia**
There was a bug when the object to be parsed contains a field of `undefined`. For example, to parse the object:
```js
$("#json").JSONView({
    x: undefined
});
```
There would be a type error
```
jquery.jsonview.js:39 Uncaught TypeError: Cannot read property 'call' of undefined
```
at
```js
return this["" + valueType + "ToHTML"].call(this, value, level);
```

This pull request fixed this bug.

### CODE REVIEW

**Comment by Justineo** [comment]
`undefined` is not valid JSON.

**Comment by Ovilia** [comment]
@Justineo This makes sense...
I use this lib to parse js object rather than json. 
If the author rejects this PR, he'd better give more information when error occurs.
Thanks.

**Comment by yesmeck** [comment]
Thanks for the PR, I'm on my vocation now, I will take a look on this weekend.

**Comment by Ovilia** [comment]
@yesmeck Sure. Nice trip! 😄

**Pull request merged**
